import mongoose from 'mongoose';
import jwt from 'jsonwebtoken';

const playerSchema = new mongoose.Schema({
  playerId: String,
  name: {
    type: String,
    required: true
  },
  role: {
    type: String,
    enum: ['batsman', 'bowler', 'allrounder', 'wicketkeeper'],
    default: 'batsman'
  }
}, { _id: false });

const teamSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  players: [playerSchema]
}, { _id: false });

const matchSchema = new mongoose.Schema({
  matchId: {
    type: String,
    required: false,  // Auto-generated by pre-save hook
    unique: true,
    index: true
  },
  tournamentId: {
    type: String,
    ref: 'Tournament',
    required: true,
    index: true
  },
  scorerToken: {
    type: String,
    required: false  // Auto-generated by pre-save hook
  },
  team1: {
    type: teamSchema,
    required: true
  },
  team2: {
    type: teamSchema,
    required: true
  },
  tossWinner: {
    type: String,
    required: true
  },
  tossDecision: {
    type: String,
    enum: ['bat', 'bowl'],
    required: true
  },
  matchType: {
    type: String,
    default: 'Custom'
  },
  overs: {
    type: Number,
    required: true,
    min: 1
  },
  customRules: {
    declareOneEnabled: {
      type: Boolean,
      default: false
    }
  },
  currentInnings: {
    type: Number,
    enum: [1, 2],
    default: 1
  },
  status: {
    type: String,
    enum: ['not_started', 'live', 'innings_break', 'completed'],
    default: 'not_started'
  },
  result: {
    type: String,
    default: ''
  },
  winner: {
    type: String,
    default: ''
  }
}, {
  timestamps: true
});

// Auto-generate match ID
matchSchema.pre('save', async function(next) {
  if (!this.matchId) {
    const year = new Date().getFullYear();
    const count = await mongoose.model('Match').countDocuments();
    this.matchId = `M-${year}-${String(count + 1).padStart(3, '0')}`;
  }

  // Generate scorer token if not exists
  if (!this.scorerToken) {
    this.scorerToken = jwt.sign(
      { matchId: this.matchId },
      process.env.JWT_SECRET || 'your-secret-key',
      { expiresIn: '7d' }
    );
  }

  next();
});

// Method to verify scorer token
matchSchema.methods.verifyToken = function(token) {
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'your-secret-key');
    return decoded.matchId === this.matchId;
  } catch (error) {
    return false;
  }
};

const Match = mongoose.model('Match', matchSchema);

export default Match;
