import mongoose from 'mongoose';
import bcrypt from 'bcrypt';

const tournamentSchema = new mongoose.Schema({
  tournamentId: {
    type: String,
    required: false,  // Auto-generated by pre-save hook
    unique: true,
    index: true
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  organizerName: {
    type: String,
    required: true,
    trim: true
  },
  customRules: {
    declareOneEnabled: {
      type: Boolean,
      default: false
    }
  },
  matches: [{
    type: String,
    ref: 'Match'
  }],
  scorerPin: {
    type: String,
    select: false
  },
  status: {
    type: String,
    enum: ['upcoming', 'ongoing', 'completed'],
    default: 'upcoming'
  }
}, {
  timestamps: true
});

// Auto-generate tournament ID
tournamentSchema.pre('save', async function(next) {
  if (!this.tournamentId) {
    const year = new Date().getFullYear();
    const last = await mongoose.model('Tournament')
      .findOne({ tournamentId: { $regex: `^T-${year}-` } })
      .sort({ tournamentId: -1 })
      .select('tournamentId');
    const lastNum = last ? parseInt(last.tournamentId.split('-')[2], 10) : 0;
    this.tournamentId = `T-${year}-${String(lastNum + 1).padStart(3, '0')}`;
  }
  next();
});

// Verify a plain-text PIN against the stored hash
tournamentSchema.methods.verifyPin = async function(pin) {
  if (!this.scorerPin) return false;
  return bcrypt.compare(pin, this.scorerPin);
};

// Hash a plain-text PIN
tournamentSchema.statics.hashPin = async function(pin) {
  return bcrypt.hash(pin, 10);
};

const Tournament = mongoose.model('Tournament', tournamentSchema);

export default Tournament;
